const styles = StyleSheet.create({
  backgroundImage: { flex: 1, width: "100%", height: "100%" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  container: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
    paddingVertical: 40,
  },
  card: {
    width: "100%",
    maxWidth: 450,
    backgroundColor: "rgba(15, 23, 42, 0.85)",
    borderRadius: 24,
    padding: 25,
    borderWidth: 1,
    borderColor: "rgba(139, 92, 246, 0.5)",
    shadowColor: "#8b5cf6",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 15,
  },
  headerContainer: { alignItems: "center", marginBottom: 25 },
  logoIcon: {
    width: 64,
    height: 64,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  title: { fontSize: 24, fontWeight: "bold", color: "white", marginBottom: 6 },
  subtitle: { fontSize: 13, color: "#94a3b8", textAlign: "center" },
  rolesContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  roleButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    marginHorizontal: 4,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 2,
    borderColor: "transparent",
  },
  roleText: {
    color: "#94a3b8",
    fontSize: 13,
    fontWeight: "600",
    marginLeft: 8,
  },
  formContainer: { width: "100%" },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  halfInputContainer: { width: "48%" },
  fullInputContainer: { width: "100%", marginBottom: 12 },
  label: { fontSize: 12, fontWeight: "600", color: "#e2e8f0", marginBottom: 6 },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 14,
    height: 48,
  },
  inputIcon: { paddingLeft: 12, marginRight: 8 },
  input: { flex: 1, color: "white", fontSize: 13, height: "100%" },
  errorText: { color: "#f87171", fontSize: 11, marginTop: 2 },
  serverError: {
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    borderColor: "rgba(239, 68, 68, 0.3)",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
  },
  serverErrorText: { color: "#f87171", fontSize: 13 },
  submitButton: {
    backgroundColor: "#10b981",
    borderRadius: 14,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 15,
  },
  disabledButton: { opacity: 0.7 },
  submitButtonText: { color: "white", fontSize: 15, fontWeight: "bold" },
  loginLink: { marginTop: 20, alignItems: "center" },
  loginText: { color: "#94a3b8", fontSize: 13 },
  loginTextBold: { color: "#8b5cf6", fontWeight: "bold" },
  closeBtn: {
    alignSelf: "flex-end",
    padding: 8,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 20,
    marginBottom: 5,
  },

  /* OTP Verification UI styles */
  backBtnCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(139, 92, 246, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  iconWrapper: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "rgba(139, 92, 246, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  otpContainer: {
    width: "100%",
    alignItems: "center",
    marginVertical: 12,
  },
  otpBoxesRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 6,
  },
  otpBox: {
    width: 44,
    height: 52,
    borderRadius: 12,
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  otpBoxActive: {
    borderColor: "#8b5cf6",
    backgroundColor: "rgba(139, 92, 246, 0.12)",
    shadowColor: "#8b5cf6",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  otpBoxFilled: {
    borderColor: "#8b5cf6",
    backgroundColor: "rgba(15, 23, 42, 0.9)",
  },
  otpDigit: {
    color: "white",
    fontSize: 20,
    fontWeight: "800",
  },
  hiddenOtpInput: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    opacity: 0.01,
    color: "transparent",
    backgroundColor: "transparent",
  },
  validityBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 8,
  },
  validityText: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "500",
  },
  resendContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  resendText: {
    color: "#94a3b8",
    fontSize: 14,
  },
  resendLink: {
    color: "#8b5cf6",
    fontSize: 14,
    fontWeight: "700",
  },
});
